build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests:
          override:
            -
              command: 'vendor/bin/phpunit --coverage-clover=build/clover.xml'
              coverage:
                file: 'build/clover.xml'
                format: 'clover'
filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - 'build/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
            before_keywords:
                else: false
